# Generated by Django 5.2.6 on 2025-11-24 22:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('musicapp', '0002_cover'),
    ]

    operations = [
        migrations.DeleteModel(
            name='cover',
        ),
        migrations.AddField(
            model_name='song',
            name='cover_image',
            field=models.ImageField(blank=True, null=True, upload_to='media/'),
        ),
    ]
